# Build Windows installer for KeySwitch using NSIS
# Requires: NSIS to be installed (https://nsis.sourceforge.io/)

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$Version = (Select-String -Path "$ProjectRoot\Cargo.toml" -Pattern '^version\s*=\s*"([^"]+)"').Matches[0].Groups[1].Value
$BuildDir = "$ProjectRoot\build\windows"
$DistDir = "$ProjectRoot\dist"

Write-Host "Building KeySwitch Windows installer v$Version..." -ForegroundColor Green

# Clean and create build directories
if (Test-Path $BuildDir) {
    Remove-Item -Recurse -Force $BuildDir
}
New-Item -ItemType Directory -Force -Path "$BuildDir\files" | Out-Null
New-Item -ItemType Directory -Force -Path $DistDir | Out-Null

# Build the release binary
Write-Host "Building release binary..." -ForegroundColor Cyan
Set-Location $ProjectRoot
cargo build --release

# Copy binary
Write-Host "Copying files..." -ForegroundColor Cyan
Copy-Item "$ProjectRoot\target\release\keyswitch.exe" "$BuildDir\files\keyswitch.exe"

# Create NSIS installer script
$NsisScript = @"
; KeySwitch Windows Installer Script
; Generated by build-windows-installer.ps1

!include "MUI2.nsh"
!include "FileFunc.nsh"

; Basic Info
Name "KeySwitch"
OutFile "$DistDir\KeySwitch-${Version}-Setup.exe"
InstallDir "`$PROGRAMFILES\KeySwitch"
InstallDirRegKey HKLM "Software\KeySwitch" "Install_Dir"
RequestExecutionLevel admin

; Modern UI Configuration
!define MUI_ABORTWARNING
!define MUI_ICON "`${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "`${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "$ProjectRoot\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "English"

; Version Info
VIProductVersion "$Version.0"
VIAddVersionKey "ProductName" "KeySwitch"
VIAddVersionKey "FileDescription" "Keychron Keyboard Auto-Switcher"
VIAddVersionKey "FileVersion" "$Version"
VIAddVersionKey "ProductVersion" "$Version"
VIAddVersionKey "LegalCopyright" "© 2026"

; Installer Section
Section "Install"
    SetOutPath "`$INSTDIR"

    ; Install files
    File "$BuildDir\files\keyswitch.exe"

    ; Write registry keys
    WriteRegStr HKLM "Software\KeySwitch" "Install_Dir" "`$INSTDIR"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch" "DisplayName" "KeySwitch"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch" "UninstallString" '"`$INSTDIR\uninstall.exe"'
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch" "DisplayVersion" "$Version"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch" "Publisher" "KeySwitch"
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch" "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch" "NoRepair" 1

    ; Create uninstaller
    WriteUninstaller "`$INSTDIR\uninstall.exe"

    ; Create startup shortcut for current user
    CreateDirectory "`$SMSTARTUP"
    CreateShortcut "`$SMSTARTUP\KeySwitch.lnk" "`$INSTDIR\keyswitch.exe" "--daemon" "" "" SW_SHOWMINIMIZED

    ; Start the daemon now
    Exec '"`$INSTDIR\keyswitch.exe" --daemon'

    MessageBox MB_OK "KeySwitch has been installed successfully!`n`nThe daemon will start automatically when you log in.`n`nTo view logs, check: `$TEMP\keyswitch.log"
SectionEnd

; Uninstaller Section
Section "Uninstall"
    ; Kill the daemon if running
    nsExec::Exec 'taskkill /F /IM keyswitch.exe'

    ; Remove startup shortcut
    Delete "`$SMSTARTUP\KeySwitch.lnk"

    ; Remove files
    Delete "`$INSTDIR\keyswitch.exe"
    Delete "`$INSTDIR\uninstall.exe"
    RMDir "`$INSTDIR"

    ; Remove registry keys
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KeySwitch"
    DeleteRegKey HKLM "Software\KeySwitch"

    MessageBox MB_OK "KeySwitch has been uninstalled."
SectionEnd
"@

$NsisScript | Out-File -FilePath "$BuildDir\installer.nsi" -Encoding ASCII

# Build installer with NSIS
Write-Host "Building installer with NSIS..." -ForegroundColor Cyan

# Try to find NSIS
$NsisPath = $null
$PossiblePaths = @(
    "C:\Program Files (x86)\NSIS\makensis.exe",
    "C:\Program Files\NSIS\makensis.exe",
    "$env:ProgramFiles\NSIS\makensis.exe",
    "${env:ProgramFiles(x86)}\NSIS\makensis.exe"
)

foreach ($Path in $PossiblePaths) {
    if (Test-Path $Path) {
        $NsisPath = $Path
        break
    }
}

if (-not $NsisPath) {
    Write-Host ""
    Write-Host "ERROR: NSIS not found!" -ForegroundColor Red
    Write-Host "Please install NSIS from https://nsis.sourceforge.io/Download" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Alternative: Use WiX Toolset or create a simple ZIP package" -ForegroundColor Yellow
    exit 1
}

& $NsisPath "$BuildDir\installer.nsi"

Write-Host ""
Write-Host "✅ Installer created successfully!" -ForegroundColor Green
Write-Host "📦 Location: dist\KeySwitch-${Version}-Setup.exe" -ForegroundColor Cyan
Write-Host ""
Write-Host "Users can install by double-clicking the .exe file" -ForegroundColor Yellow
